---
# role: ansible-role-chrony
# file: tasks/tasks.yml

- name: "Remove conflicting packages"
  package:
    name: "{{ chrony_remove_packages }}"
    state: absent

- name: "Install packages for ansible-role-chrony"
  package:
    name: "{{ chrony_packages }}"
    state: present

- name: "Stop conflicting services"
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ chrony_mask_services }}"

- name: "Mask conflicting services in systemd"
  service:
    name: "{{ item }}"
    enabled: false
    masked: true
    state: stopped
  loop: "{{ chrony_mask_services }}"
  when: ansible_service_mgr == 'systemd'

- name: "Write {{ chrony_conf }}"
  template:
    src: "etc/chrony.conf.j2"
    dest: "{{ chrony_conf }}"
    owner: root
    group: root
    mode: 0644
  notify: enable and restart chronyd
