---
# role: ansible-role-chrony
# file: tasks/tasks.yml

- name: "Set os_family dependent variables"
  include_vars: '{{ ansible_os_family }}.yml'

- name: "Set distribution dependent variables"
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: "Remove ntp packages"
  package:
    name: "{{ chrony_remove_packages }}"
    state: absent

- name: "Install packages for ansible-role-chrony"
  package:
    name: "{{ chrony_packages }}"
    state: present

- name: "Import chrony client tasks"
  import_tasks: client.yml
