---
# role: ansible-role-chrony
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-chrony
    box: "generic/alpine312"
    cpus: 2
    memory: 1024
  - name: amazon-chrony
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: arch-chrony
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: centos-chrony
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: debian-chrony
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: fedora-chrony
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: opensuse-chrony
    box: "generic/opensuse15"
    cpus: 2
    memory: 1024
  - name: oracle-chrony
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: ubuntu-chrony
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
