---
# role: ansible-role-chrony
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: arch-chrony
    box: "archlinux/archlinux"
    cpus: 2
    memory: 2048
  - name: centos-chrony
    box: "centos/8"
    cpus: 2
    memory: 2048
  - name: debian-chrony
    box: "debian/bullseye64"
    cpus: 2
    memory: 2048
  - name: fedora-chrony
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 2048
  - name: opensuse-chrony
    box: "generic/opensuse15"
    cpus: 2
    memory: 2048
  - name: oracle-chrony
    box: "generic/oracle8"
    cpus: 2
    memory: 2048
  - name: ubuntu-chrony
    box: "generic/ubuntu2004"
    cpus: 2
    memory: 2048
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
