---
# role: ansible-role-chrony
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 2048
      cpus: 2
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: arch-chrony
    box: "archlinux/archlinux"
  - name: centos-chrony
    box: "centos/8"
  - name: debian-chrony
    box: "debian/bullseye64"
  - name: fedora-chrony
    box: "fedora/33-cloud-base"
  - name: opensuse-chrony
    box: "generic/opensuse15"
  - name: oracle-chrony
    box: "generic/oracle8"
  - name: ubuntu-chrony
    box: "generic/ubuntu2004"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        chrony_role_enabled: true
verifier:
  name: ansible
