---
# role: ansible-role-chrony
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: default-chrony
    image: "${uns:-jam82}/molecule-${img:-debian}:${tag:-latest}"
    command: ""
    pre_build_image: true
    tty: false
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        chrony_role_enabled: true
verifier:
  name: ansible
