---
# role: ansible-role-chrony
# file: molecule/resources/playbooks/verify.yml

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Run chrony sync"
      command: chronyc -a 'burst 4/4'
      changed_when: false

    - name: "Wait 5 seconds"
      pause:
        seconds: 5

    - name: "Run chrony makestep"
      command: chronyc -a makestep
      changed_when: false
      failed_when: false

    - name: "Check chrony tracking"
      command: chronyc tracking
      changed_when: false
      register: chrony_tracking

    - name: "Assertions"
      assert:
        that:
          - chrony_tracking.rc == 0
          - "'Not synchronised' not in chrony_tracking.stdout"
