---
# role: ansible-role-chrony
# file: molecule/tox/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: molecule/tox/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: chrony-${TOX_ENVNAME:-"default"}
    image: "${uns:-jam82}/molecule-${img:-debian}:${tag:-latest}"
    command: ""
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
